image: node:latest

stages:
  - build
  - test

variables:
  GIT_STRATEGY: clone


cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 24 hrs

linting:
  stage: test
  script: npm run lint

testing:
  stage: test
  script: npm run test